### ISSUE TITLE
Raspberry Pi 2

### ISSUE THREAD

**Issue by Audiogeek1974** [magdesign/PocketVJ#7]
Is there an image to get this to run on a Raspberry Pi 2? 

I tried following all the steps here, but it is for a 3.
https://gist.github.com/baydam/a905e4878f54150f7da421e2c1d17a21

After that, I can get to the web page but the Pi seems to still just boot to the normal prompt. It isn't running anything in the background. Any ideas?

**Comment by magdesign** [comment]
RaspberryPI 2 is not supported on PVJ 1.x as written in the README.md
